name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "flake8_isort.py"
      - "test_flake8_isort.py"
      - "setup.py"
      - ".github/workflows/tests.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }} x isort ${{ matrix.isort }} x flake8 ${{ matrix.flake8 }}

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', 'pypy3']
        isort: [4.3.21, 5.9.3]
        flake8: [3.9.2, 4.0.1]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install matrix dependencies
        run: pip install 'isort==${{ matrix.isort }}' 'flake8==${{ matrix.flake8 }}'
      - name: Install dependencies
        run: pip install .[test]
      - name: flake8
        run: flake8 *.py
      - name: pytest
        run: pytest -v --cov flake8_isort --cov-report term-missing
      - name: Upload coverage
        run: |
          python -m pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
